MvcCoreLinqToSQL/Models/Empleado.cs
namespace MvcCoreLinqToSQL.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvcCoreLinqToSQL/Models/Enfermo.cs
namespace MvcCoreLinqToSQL.Models
{
    public class Enfermo
    {
        public string Inscipcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public string NumeroSeguridadSocial { get; set; }
        
    }
}

MvcCoreLinqToSQL/Models/ErrorViewModel.cs
namespace MvcCoreLinqToSQL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreLinqToSQL/Models/ResumenEmpleados.cs
namespace MvcCoreLinqToSQL.Models
{
    public class ResumenEmpleados
    {
        public int Personas { get; set; }
        public int MaximoSalario { get; set; }
        public double MediaSalario { get; set; }
        public List<Empleado> Empleados { get; set; }
    }
}

MvcCoreLinqToSQL/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL.Models;
using MvcCoreLinqToSQL.Repositories;

namespace MvcCoreLinqToSQL.Controllers
{
    public class EmpleadosController : Controller
    {
        RepositoryEmpleados repo;

        public EmpleadosController()
        {
            this.repo = new RepositoryEmpleados();
        }

        public IActionResult Index()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Details(int idempleado)
        {
            Empleado emp = this.repo.FindEmpleado(idempleado);
            return View(emp);
        }

        public IActionResult BuscadorEmpleados()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BuscadorEmpleados(string oficio, int salario)
        {
            List<Empleado> empleados = this.repo.GetEmpleadosOficioSalario(oficio, salario);

            if (empleados == null)
            {
                ViewData["MENSAJE"] = "No existen empleados con estas condiciones";
                return View();
            }
            else
            {
                return View(empleados);
            }

        }

        public IActionResult EmpleadosOficio()
        {
            ViewData["oficios"] = this.repo.GetOficios();
            
            return View();
        }

        [HttpPost]
        public IActionResult EmpleadosOficio(string oficio)
        {
            ResumenEmpleados resumen = this.repo.GetEmpleadosOficio(oficio);
            ViewData["oficios"] = this.repo.GetOficios();

            return View(resumen);
        }
    }
}

MvcCoreLinqToSQL/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL.Models;
using MvcCoreLinqToSQL.Repositories;

namespace MvcCoreLinqToSQL.Controllers
{
    public class EnfermosController : Controller
    {
        RepositoryEnfermos repo;

        public EnfermosController()
        {
            this.repo = new RepositoryEnfermos();
        }

        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.repo.GetEnfermos();
            return View(enfermos);
        }

        public IActionResult Details(string inscripcion)
        {
            Enfermo enfermo = this.repo.FindEnfermo(inscripcion);
            return View(enfermo);
        }

        public  IActionResult Delete(string inscripcion)
        {
            this.repo.DeleteEnfermo(inscripcion);
            return RedirectToAction("Index");
        }
    }
}

MvcCoreLinqToSQL/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL.Models;

namespace MvcCoreLinqToSQL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreLinqToSQL/Views/Empleados/BuscadorEmpleados.cshtml
@model List<Empleado>

<h1>
	Buscador de empleados por oficio y salario
</h1>

<form method="post">
	<label>Oficio: </label>
	<input type="text" name="oficio" value="" class="form-control"/>

	<label>Salario: </label>
	<input type="number" name="salario" value="" class="form-control"/>

	<button class="btn btn-success">
		Buscar
	</button>
</form>

<h2>@ViewData["MENSAJE"]</h2>

@if(Model != null){
<table class="table table-striped">
	<thead>
		<tr>
			<th>Apellido</th>
			<th>Oficio</th>
			<th>Salario</th>
			<th>Detalles</th>
		</tr>
	</thead>
	<tbody>
		@foreach (Empleado empleado in Model)
		{
			<tr>
				<td>@empleado.Apellido</td>
				<td>@empleado.Oficio</td>
				<td>@empleado.Salario</td>
				<td><a asp-controller="Empleados" asp-action="Details" asp-route-idempleado="@empleado.IdEmpleado" class="btn btn-info">Details</a></td>
			</tr>
		}
	</tbody>
</table>
}

MvcCoreLinqToSQL/Views/Empleados/Details.cshtml
@model Empleado

<h1>Detalles Empleado</h1>

<ul class="list-group">
    <li class="list-group-item">
       Apellido: @Model.Apellido
    </li>
    <li class="list-group-item">
        Oficio: @Model.Oficio
    </li>
    <li class="list-group-item">
        Salario: @Model.Salario
    </li>
    <li class="list-group-item">
        Departamento: @Model.IdDepartamento
    </li>
</ul>

MvcCoreLinqToSQL/Views/Empleados/EmpleadosOficio.cshtml
@model ResumenEmpleados
@{
	List<string> oficios = ViewData["oficios"] as List<string>;
}

<h1>Empleados oficio</h1>

<form method="post">
	<label>Oficio:</label>
	<select name="oficio" class="form-control">
		@foreach(string oficio in oficios){
			<option value="@oficio">@oficio</option>
		}
	</select>
	<button class="btn btn-dark">Buscar</button>
</form>

@if(Model != null){
	<ul class="list-group">
		<li class="list-group-item">
			Personas: @Model.Personas
		</li>
		<li class="list-group-item">
			Maximo salario: @Model.MaximoSalario
		</li>
		<li class="list-group-item">
			Media salario: @Model.MediaSalario
		</li>
	</ul>
	<table class="table table-striped">
		<thead>
			<tr>
				<td>Apellido</td>
				<td>Oficio</td>
				<td>Salario</td>
			</tr>
		</thead>
		<tbody>
			@foreach(Empleado empleado in Model.Empleados){
				<tr>
					<td>@empleado.Apellido</td>
					<td>@empleado.Oficio</td>
					<td>@empleado.Salario</td>
				</tr>
			}
		</tbody>
	</table>
}

MvcCoreLinqToSQL/Views/Empleados/Index.cshtml
@model List<Empleado>

<h1>Linq Empleados</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Apellido</th>
			<th>Oficio</th>
			<th>Salario</th>
			<th>Detalles</th>
		</tr>
	</thead>
	<tbody>
		@foreach(Empleado empleado in Model){
			<tr>
				<td>@empleado.Apellido</td>
				<td>@empleado.Oficio</td>
				<td>@empleado.Salario</td>
				<td><a asp-controller="Empleados" asp-action="Details" asp-route-idempleado="@empleado.IdEmpleado" class="btn btn-info">Details</a></td>
			</tr>
		}
	</tbody>
</table>

MvcCoreLinqToSQL/Views/Enfermos/Details.cshtml
@model Enfermo

<h1>Detalles @Model.Apellido</h1>

<ul class="list-group">
    <li class="list-group-item">
        Numero de inscripcion: @Model.Inscipcion
    </li>
    <li class="list-group-item">
        Apellido: @Model.Apellido
    </li>
    <li class="list-group-item">
        Direccion: @Model.Direccion
    </li>
    <li class="list-group-item">
        Fecha de Nacimiento: @Model.FechaNacimiento
    </li>
    <li class="list-group-item">
        Genero: @Model.Genero
    </li>
    <li class="list-group-item">
        Numero de la Seguridad Social: @Model.NumeroSeguridadSocial
    </li>
</ul>

MvcCoreLinqToSQL/Views/Enfermos/Index.cshtml
@model List<Enfermo>

<h1>Listado de enfermos</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Apellido</th>
			<th>Direccion</th>
			<th>Fecha Nacimineto</th>
			<th>Genero</th>
			<th>Detalles</th>
			<th>Borrar</th>
		</tr>
	</thead>
	<tbody>
		@foreach (Enfermo enfermo in Model)
		{
			<tr>
				<td>@enfermo.Apellido</td>
				<td>@enfermo.Direccion</td>
				<td>@enfermo.FechaNacimiento</td>
				<td>@enfermo.Genero</td>
				<td><a asp-controller="Enfermos" asp-action="Details" asp-route-inscripcion="@enfermo.Inscipcion" class="btn btn-info">Details</a></td>
				<td><a asp-controller="Enfermos" asp-action="Delete" asp-route-inscripcion="@enfermo.Inscipcion" class="btn btn-danger">Borrar</a></td>
			</tr>
		}
	</tbody>
</table>

MvcCoreLinqToSQL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreLinqToSQL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreLinqToSQL</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreLinqToSQL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreLinqToSQL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="BuscadorEmpleados">Buscador Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="Index">Enfermos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="EmpleadosOficio">Empleados oficio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcCoreLinqToSQL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>